# Generated by Django 4.1.3 on 2022-11-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="data_cretaed",
            new_name="data_created",
        ),
    ]
